### ISSUE TITLE
Support for multiple inputs

### ISSUE THREAD

**Issue by jawoznia** [tonyfinn/runtime-macros-derive#102]
Hi, would it be possible to develop this lib to work with multiple Token Stream inputs?
My use case requires two TS as arguments passed to macros, but unfortunately your lib works only with single argument macros.

**Comment by tonyfinn** [comment]
Do you have an example macro implementation to show what you mean?

**Comment by jawoznia** [comment]
Issue was regarding attribute-like macros coverage. It was though implemented recently in https://github.com/jeremydavis519/runtime-macros from which you forked.

You might want to rebase to those changes.

**Comment by tonyfinn** [comment]
Fair enough. Another user has contributed them to this project seperately, and the changes here were initially proposed to the original package but the PR was left hanging for a year. 

Now upstream is alive again, the functionality of the two projects (it's a pretty small library) is pretty equivalent but I'll leave this one up for people who want to keep api compatibility, or they can use runtime-macros for shorter method names
